services:
  api:
    build:
      context: .
    ports: ["8000:8000"]
    env_file: [.env]
    volumes:
      - ./app:/app/app
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
